vision_imx500:
  enabled: true
  environment: robot
  path: 'modules.vision.imx500.vision.vision.Vision'
  config:
    preview: false
  dependencies:
    unix:
      - imx500-all
    python:
      - opencv-python
    # additional:
      # - "add dtoverlay=imx500-pi5,cam0 to /boot/firmware/config.txt"
