bno055:
  enabled: true
  environment: robot
  path: modules.sensor.imu.bno055.bno055.BNO055
  instances:
    - name: "imu_head"
      test_on_boot: false
      address: 0x28
    - name: "imu_body"
      test_on_boot: false
      line_offset: 1
      address: 0x29
  dependencies:
    python:
      - adafruit-circuitpython-bno055
      - adafruit-blinka
