bno055:
  instances:
  - name: imu_head
    test_on_boot: false
    address: 0x28
  - name: imu_body
    test_on_boot: false
    line_offset: 1
    address: 0x29
  dependencies:
    python:
    - adafruit-circuitpython-bno055
    - adafruit-blinka
  class: BNO055
