bno055:
  enabled: true
  environment: robot
  path: modules.bno055_imu.BNO055
  instances:
    - name: "imu_head"
      test_on_boot: false
      bus: 1
      address: 0x28
    - name: "imu_body"
      test_on_boot: false
      bus: 1
      line_offset: 1
      address: 0x29
  dependencies:
    unix:
      - python3-smbus
    python:
      - smbus
      - adafruit-circuitpython-bno055
      - adafruit-blinka
