controller:
  enabled: true
  path: 'modules.controller.Controller'
  config:
    deadzone: 500
    modifier_buttons:
      - BTN_TL
      - BTN_TR
    button_action_map:
      default:
        BTN_TL:
          - topic: ''
            args: {}
        BTN_TR:
          - topic: ''
            args: {}
        BTN_SELECT:
          - topic: 'record/stop'
            args: {}
        BTN_START:
          - topic: 'record/start'
            args: {}
        KEY_RECORD: # Only on Xbox S/X remotes
          - topic: ''
            args: {}
        BTN_MODE: # Xbox Logo
          - topic: ''
            args: {}
        ABS_HAT0X: # DPAD X (-1, 0 or 1)
          - topic: ''
            args: {}
        ABS_HAT0Y: # DPAD Y (-1, 0 or 1)
          - topic: ''
            args: {}
        BTN_A:
          - topic: 'tts'
            args: {
              msg: 'Test Default'
            }
        BTN_X:
          - topic: 'eye/blink'
            args: {}
        BTN_Y:
          - topic: 'gpio/laser/toggle'
            args: {}
        BTN_B:
          - topic: ''
            args: {}
        ABS_RZ:
          - topic: 'servo:pan:mv'
            args: {}
            deadzone: 200
            modifier:
              scale: 0.01
        ABS_RX:
          - topic: 'servo:tilt:mv'
            args: {}
            modifier:
              scale: -0.01
        ABS_X:
          - topic: 'eye/move'
            args: {axis: 'y'}
            modifier:
              scale: -0.03
        ABS_Y:
          - topic: 'eye/move'
            args: {axis: 'x'}
            modifier:
              scale: -0.03
        ABS_Z: # Left trigger
          - topic: ''
            args: {}
        ABS_RY: # Right trigger
          - topic: ''
            args: {}
      BTN_TR:
        BTN_A:
          - topic: 'tts'
            args: {
              msg: 'Left Shoulder Held'
            }
        ABS_X:
          - topic: 'servo:leg_l_ankle:mv'
            modifier:
              scale: 1.0
          - topic: 'servo:leg_r_ankle:mv'
            modifier:
              scale: -1.0
          - topic: 'servo:leg_l_knee:mv'
            modifier:
              scale: 1.0
          - topic: 'servo:leg_r_knee:mv'
            modifier:
              scale: -1.0
          - topic: 'servo:leg_l_hip:mv'
            modifier:
              scale: 1.0
          - topic: 'servo:leg_r_hip:mv'
            modifier:
              scale: -1.0
