tft_display:
  enabled: true
  environment: robot
  path: modules.display.waveshare_oled.WaveshareOLED
  config:
    test_on_boot: false
    time_on_boot: false
    reset_pin: 26 # Changed directly in waveshare config.py to avoid conflict with TFT display
    dc_pin: 24 # Changed directly in waveshare config.py to avoid conflict with TFT display
  dependencies:
    unix:
      - python3-pip
      - python3-pil
      - python3-numpy
    python:
      - RPi.GPIO