piservo:
  enabled: true
  path: modules.actuators.piservo.PiServo
  instances:
    - name: "ear"
      id: 0
      pin: 22
      range: [-40, 40]
      start: 0
      test_on_boot: false
  dependencies:
    python:
      - gpiozero
