servos:
  enabled: true
  environment: robot
  path: "modules.actuators.bus_servo.servo.Servo" # Include class name here
  instances:
    - name: "leg_r_tilt"
      model: 'ST3215'
      id: 1
      range: [978, 3343]
      start: 3187
    - name: "leg_r_hip"
      model: 'ST3215'
      id: 3
      range: [770, 3389]
      # start: 1736 # tand?
      start: 2911 # straight forward
    - name: "leg_r_knee"
      model: 'ST3215'
      id: 2
      range: [750, 3297]
      start: 1345
    - name: "leg_r_ankle"
      model: 'ST3215'
      id: 6
      range: [2459, 3872]
      start: 2762
    - name: "neck_pan"
      model: 'SC09'
      baudrate: 115200
      id: 5
      range: [0, 1023]
      start: 511
      # calibrate_on_boot: true
      demonstrate_on_boot: true
      speed: 300 # tested up to 600
      acceleration: 1
    - name: "neck_tilt"
      model: 'SC09'
      baudrate: 115200
      id: 11
      range: [0, 240] # 70 degree
      start: 120
      speed: 300 # max=0, 1 - 3000 tested
      # acceleration: 0 # max (no significant difference between this and 1 - 3000)
      demonstrate_on_boot: true
    - name: "neck_tilt2"
      model: 'SC09'
      baudrate: 115200
      id: 4
      range: [0, 610] # 180 degree (may need reducing)
      start: 305
      speed: 300
      # acceleration: 1
      # demonstrate_on_boot: true
    - name: "leg_l_tilt"
      model: 'ST3215'
      id: 7
      range: [812, 2076]
      start: 1093
    - name: "leg_l_hip"
      model: 'ST3215'
      id: 8
      range: [747, 3370]
      # start: 2388 # stand?
      start: 1180 # straight forward
    - name: "leg_l_knee"
      model: 'ST3215'
      id: 9
      range: [1725, 3404]
      start: 2643
    - name: "leg_l_ankle"
      model: 'ST3215'
      id: 10
      range: [874, 2270]
      start: 1566