messaging_service:
  config:
    protocol: pubsub
    mqtt_host: localhost
    mqtt_port: 1883
  dependencies:
    python:
    - paho-mqtt
    - pypubsub
    unix:
    - mosquitto
  class: MessagingService
